#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

use Data::Dumper;
use App::Verm qw< verm verl >;

my( $module, $version ) = @ARGV;

unless( defined $module ){ `perldoc $0`;exit }

my $m = verm($module);

if( defined $version ){ 
    my @p = grep{ $_->{version} =~ /.?$version$/ } @{$m};
    say "https://cpan.metacpan.org/authors/id/$p[0]->{path}/$p[0]->{author}/$p[0]->{dist}.tar.gz";
} else { 
    print Dumper $m;
    my $l = {};
    $l->{local} = verl($module);
    print Dumper $l;
}

=head1 NAME

verm - get specific version of distribution

=head1 DESCRIPTION

Use module name as 1st parameter to print module versions. Add specific version as 2nd parameter and pipe it to cpanm to install it. 

=head1 SYSOPSIS

Print all versions of module distribution

C<verm Module>

Then use cpanm to install specific version.

C<verm Module version | cpanm>

=head1 DEPENDENCIES

C<App::cpanminus>, libssl

=cut
